document.getElementById('fortalezas').innerHTML = `
    <p>Durante mi servicio comunitario en la fundación desempeñándome como acompañante académico en materias como física, química y matemáticas descubrí tres fortalezas individuales que resultaron fundamentales para el éxito de las actividades: paciencia, comunicación efectiva y empatía. Ya que la paciencia fue esencial para explicar conceptos complejos de múltiples maneras hasta asegurarme de que los miembros de la fundación los comprendieran plenamente. Cabe mencionar que esta capacidad me permitió manejar las diversas velocidades de aprendizaje sin frustrarme y a su vez mantener un ambiente de enseñanza positivo al igual que alentador.</p>
    <p>Además, mi habilidad para comunicarme de manera clara y efectiva facilitó la transmisión de conocimientos. Usé ejemplos prácticos como el simbolismo de las matemáticas y analogías que resonaron con los estudiantes al enseñar física con conceptos de fútbol, lo que hizo que los conceptos difíciles fueran más accesibles. Esta destreza en la comunicación combinada con mi empatía me permitió entender mejor las dificultades y preocupaciones de los beneficiarios; por ende, se creó un ambiente de apoyo y comprensión.</p>
    <p>La empatía fomentó una relación de confianza motivando a los beneficiarios a participar activamente y a no temer hacer preguntas.</p>
    <p>Los chicos de la fundación también aportaron significativamente al proceso de aprendizaje con sus propias fortalezas: respeto, resiliencia y honestidad. Su respeto hacia mí y hacia sus compañeros creó un ambiente de aprendizaje positivo y colaborativo, facilitando la comunicación abierta al igual que el intercambio de ideas. Inclusive, a pesar de los desafíos académicos que enfrentaban demostraron una notable resiliencia. Debido a que, los adolescentes persistieron en su esfuerzo por entender los temas difíciles, dicha resiliencia fue inspiradora y alentó una actitud de perseverancia.</p>
    <p>La honestidad de los chicos al expresar sus dificultades o sus dudas permitió identificar áreas específicas donde necesitaban más apoyo lo que, permitía la personalización de las sesiones de acompañamiento académico para abordar sus necesidades particulares. Además, esta honestidad facilitó una enseñanza más efectiva mejorando significativamente su comprensión y retención de los conceptos. Empezando con solventar las bases teóricas de las ciencias experimentales al igual que, el enseñarles técnicas específicas para entender las mismas.</p>
    <p>La combinación de mis fortalezas individuales con las de los compañeros de la fundación creó un ambiente de aprendizaje efectivo y colaborativo. Ya que, mi paciencia, comunicación efectiva acompañado de la empatía se complementaron perfectamente con su respeto, resiliencia y honestidad, en consecuencia, se obtuvo un servicio comunitario exitoso al igual que, beneficioso para todos los involucrados. Juntos, logramos superar barreras, construir conocimiento y fortalecer nuestras habilidades, demostrando que el trabajo en equipo acompañado del apoyo mutuo es fundamental para el desarrollo académico y personal.</p>   
`;

document.getElementById('aportes').innerHTML = `
    <p>Durante mi servicio comunitario en la fundación, tuve la oportunidad de colaborar en diversas actividades que no solo beneficiaron a los miembros de la organización sino que también me permitieron aplicar y desarrollar mis propias habilidades. Dos actividades en particular destacaron por su impacto y la colaboración que implicaron: dar clases extras de matemáticas, física y química, y participar en actividades deportivas los días viernes.</p>
    <p>En primer lugar, las clases extras de matemáticas se centraron en temas clave como sistemas de ecuaciones, ecuaciones cuadráticas, trigonometría y factoreo. Estas sesiones estaban diseñadas para complementar el aprendizaje formal de los miembros de la fundación, proporcionando un espacio adicional para resolver dudas y reforzar conceptos. Empezando con sistemas de ecuaciones, utilicé diversos métodos de resolución como el método de sustitución y el de eliminación para demostrar diferentes enfoques y a su vez encontrar soluciones.</p>
    <p>Además, la trigonometría fue otro tema crucial en nuestras sesiones, donde introduje las funciones trigonométricas básicas y sus aplicaciones en triángulos rectángulos y circunferencias. Para hacer estos conceptos más accesibles, utilicé ejemplos visuales y ejercicios interactivos que permitieron a los estudiantes visualizar y manipular los ángulos y longitudes. Finalmente, al tratar el tema del factoreo, enfoqué las clases en descomponer polinomios en factores más simples, facilitando así la resolución de ecuaciones complejas. Durante todas estas sesiones, la combinación de paciencia y comunicación efectiva resultó esencial para adaptar las explicaciones a las necesidades y niveles de comprensión de cada estudiante.</p>
    <p>En segundo lugar, la participación en actividades deportivas los días viernes se convirtió en una experiencia sumamente enriquecedora, tanto para los miembros de la fundación como para mí. Cada viernes, organizábamos partidos de fútbol y básquetbol, fomentando no solo la actividad física, sino también el trabajo en equipo y la convivencia. En el caso del fútbol, formamos equipos equilibrados y a su vez desarrollamos estrategias de juego que promovían la colaboración entre los participantes. A través de estas dinámicas, chicos no solo mejoraron sus habilidades deportivas, sino que también fortalecieron sus lazos sociales y su capacidad para trabajar en equipo.</p>
    <p>Igualmente, en los partidos de básquetbol, la estructura del juego y la necesidad de coordinar movimientos enfatizaban la importancia de la cooperación al igual que, la confianza mutua. Participar en estas actividades deportivas también me permitió desarrollar mis habilidades de liderazgo junto con las de organización. Ya que, a menudo debía coordinar los equipos, explicar las reglas y asegurarme de que todos los participantes estuvieran involucrados y disfrutando del juego.</p>
    <p>En conclusión, tanto las clases extras de matemáticas como las actividades deportivas de los viernes fueron fundamentales para el desarrollo integral de los beneficiarios de la fundación. Las clases académicas proporcionaron un apoyo crucial en áreas de dificultad mientras que, las actividades deportivas fomentaron el bienestar físico y social. La combinación de estas actividades demostró ser altamente efectiva para fortalecer tanto las habilidades cognitivas como las interpersonales de los participantes, contribuyendo de manera significativa a su crecimiento y desarrollo personal.</p>
`;

document.getElementById('objetivo').innerHTML = `
    <p>Como ciudadano socialmente responsable y estudiante de sexto semestre de Ingeniería en Biotecnología, mi objetivo de vida a futuro es contribuir al Objetivo de Desarrollo Sostenible (ODS) número 6: "Garantizar la disponibilidad de agua y su gestión sostenible y el saneamiento para todos". En particular, me propongo desarrollar tecnologías innovadoras para la purificación y desalinización de agua ya que así se puede asegurar que las comunidades con escasez de este recurso vital puedan acceder a agua potable de manera sostenible y asequible.</p>
    <p>Para alcanzar este objetivo, implementaré un diseño inverso empezando por definir el resultado deseado, el cual es la creación de un prototipo funcional de un sistema de purificación y desalinización de agua que pueda ser escalado al igual que adaptado a diferentes entornos. Evaluaré el éxito de este objetivo mediante la eficacia del sistema en términos de costo, eficiencia energética y capacidad de producción de agua potable.</p>
    <p>El primer paso en esta hoja de ruta es la investigación y adquisición de conocimientos avanzados en tecnologías de purificación y desalinización. Durante los próximos dos años, dedicaré tiempo y recursos a cursar asignaturas especializadas, además de participar en proyectos de investigación dentro de mi universidad. Esto incluirá la colaboración con profesores y expertos en el campo, así como la revisión de literatura científica e inclusive la asistencia a conferencias y seminarios relevantes.</p>
    <p>Paralelamente, durante este mismo periodo, comenzaré a diseñar y desarrollar el prototipo inicial. Utilizaré los laboratorios y recursos de mi universidad para experimentar con diferentes materiales al igual que, métodos, como membranas de filtración, procesos de ósmosis inversa y tecnologías de energía renovable para alimentar el sistema. Este desarrollo se llevará a cabo en fases, con objetivos trimestrales claramente definidos, como la construcción de un primer modelo a escala pequeña y su posterior optimización.</p>
    <p>Una vez que el prototipo inicial esté desarrollado, en los siguientes seis meses, procederé a realizar pruebas exhaustivas en laboratorio. Por lo que, las pruebas incluirán la evaluación de la eficiencia de purificación, la capacidad de producción y el análisis del costo energético. En consecuencia, realizaré ajustes y mejoras en el diseño basándome en los resultados obtenidos.</p>
    <p>A continuación, en un periodo de seis a doce meses, planearé y ejecutaré pruebas de campo en comunidades con necesidades de agua potable. Para ello, buscaré colaboraciones con organizaciones no gubernamentales y comunidades locales que estén dispuestas a participar en el proyecto piloto. La evaluación en esta fase se centrará en la adaptabilidad del sistema a diferentes condiciones ambientales, además de la aceptación por parte de las comunidades beneficiadas.</p>   
`;

document.getElementById('reflexion').innerHTML = `
    <p>¿Cómo influyó en mis propósitos de vida el trabajo comunitario realizado? </p>
    <p>La experiencia de trabajo comunitario realizada influyó significativamente en mis propósitos de vida reafirmando mi compromiso con el servicio a la comunidad y la sostenibilidad. A través de la enseñanza de matemáticas y ciencias a estudiantes en una fundación, comprendí la importancia de utilizar mis conocimientos para mejorar la calidad de vida de otros. Esto me llevó a decidir enfocar mi carrera en el desarrollo de tecnologías sostenibles como la purificación de agua, alineándome con los Objetivos de Desarrollo Sostenible. Por lo tanto, el trabajo comunitario no solo enriqueció mi perspectiva sobre el impacto social de mi profesión, sino que también consolidó mi determinación de contribuir a soluciones que beneficien a la sociedad en general.</p>
    <p>¿Qué aprendí sobre la población con la que me involucré?</p>
    <p>Durante mi tiempo en la fundación, aprendí mucho sobre la población con la que trabajé. Los estudiantes demostraron una increíble resiliencia y una honestidad conmovedora en sus interacciones. A pesar de las dificultades académicas y personales que enfrentaban, mostraron un entusiasmo y una motivación constantes por aprender y mejorar. Esta observación me enseñó la importancia de la empatía y la paciencia, ya que cada individuo tiene sus propias luchas y necesidades específicas. Asimismo, trabajar con esta población me ayudó a entender mejor las realidades y desafíos que enfrentan las comunidades menos privilegiadas, fortaleciendo mi compromiso de trabajar en soluciones que puedan aliviar sus dificultades.</p>
    <p>¿Qué habilidades blandas desarrollé al involucrarme con la organización/en la clase de PASEC? (comunicación, adaptación o flexibilidad, liderazgo, negociación, trabajo en equipo, toma de decisiones, resolución de problemas, entre otros).</p>
    <p>Finalmente, involucrarme con la organización y en la clase de PASEC me permitió desarrollar diversas habilidades blandas. La comunicación efectiva fue crucial para transmitir conocimientos de manera comprensible mientras que, la adaptación junto a la flexibilidad fue necesarias para ajustar las enseñanzas a las necesidades individuales de los estudiantes. Además, la experiencia mejoró mis habilidades de liderazgo ya que, debía coordinar actividades y motivar a los estudiantes. La negociación y a su vez la toma de decisiones también fueron esenciales para resolver conflictos, con el objetivo de asegurar un ambiente de aprendizaje positivo. En resumen, esta experiencia no solo me preparó académicamente, sino que también, me dotó de un conjunto de habilidades blandas que serán fundamentales en mi desarrollo profesional y personal.</p>
`;

document.getElementById('guion').innerHTML = `
    <p>"Hola a todos. Hoy quiero contarles un cuento sobre cómo una experiencia de servicio comunitario cambió mi vida y me preparó para el futuro. Acompáñenme en este viaje de descubrimiento y aprendizaje. Había una vez un estudiante universitario que decidió ofrecer su tiempo y conocimientos en una fundación. Enseñando matemáticas y ciencias descubrió que su propósito de vida iba más allá de los libros y exámenes. Se dio cuenta de que con paciencia y empatía podía transformar la vida de los jóvenes inspirándolos a superar sus desafíos académicos.</p>
    <p>Recuerdo claramente mi primer día en la fundación. Estaba nervioso pero también emocionado por la oportunidad de hacer una diferencia. Los estudiantes, al principio tímidos, pronto se abrieron y mostraron una gran curiosidad y deseo de aprender. Este entusiasmo me motivó a esforzarme cada día más. Pero ¿cómo influyó esto en mis propósitos de vida? Este trabajo me enseñó el valor de la perseverancia y la importancia de contribuir al bienestar de la comunidad. Decidí enfocar mi carrera en la biotecnología para desarrollar soluciones sostenibles como tecnologías para la purificación de agua, alineándome con los Objetivos de Desarrollo Sostenible. Quería que mi trabajo tuviera un impacto positivo y tangible en la sociedad."</p>
    <p>En cuanto a mi desarrollo profesional, esta experiencia fue invaluable. Aprendí a comunicar conceptos complejos de manera simple y efectiva. Además, trabajar en equipo y resolver problemas prácticos fortaleció mis habilidades de liderazgo y adaptación. Me di cuenta de que enseñar y aprender son dos caras de la misma moneda. Enseñar me obligó a profundizar en mis propios conocimientos y a encontrar nuevas formas de explicar conceptos difíciles.</p>
    <p>Además, trabajar en un entorno diverso me enseñó mucho sobre la importancia de la inclusión y la diversidad. Cada estudiante tenía una historia única y diferentes desafíos. Sus historias de superación personal me enseñaron a no juzgar y a siempre buscar entender las circunstancias de los demás.</p>
    <p>También aprendí mucho sobre la población con la que trabajé. Los estudiantes mostraron una increíble resiliencia y una honestidad conmovedora en sus interacciones. Su entusiasmo por aprender y mejorar sus habilidades me inspiró cada día. Estas experiencias me recordaron la importancia de la educación y cómo un buen mentor puede cambiar la vida de un estudiante.</p>
    <p>Al final del día, me di cuenta de que el impacto que tenía en estos estudiantes era solo una parte de la historia. Ellos también estaban moldeándome, preparándome para un futuro en el que podría usar mis habilidades para el bien común. Cada sonrisa, cada momento de comprensión y cada pequeña victoria en el aula me recordaron por qué había elegido este camino.</p>
    <p>Espero que esta historia les inspire a buscar oportunidades de servicio comunitario y a ver el valor que puede aportar a sus vidas y carreras. La experiencia de dar es una que devuelve mucho más de lo que uno podría imaginar.</p>
`;

// JavaScript para manejar el despliegue de contenido
document.querySelectorAll('.toggle-button').forEach(button => {
    button.addEventListener('click', () => {
        const targetId = button.getAttribute('data-target');
        const targetElement = document.getElementById(targetId);
        
        if (targetElement.style.display === 'none' || targetElement.style.display === '') {
            targetElement.style.display = 'block';
        } else {
            targetElement.style.display = 'none';
        }
    });
});
